backend:
  name: turbo-github
  turbo_site_id: 0d16319b-cd7d-4be8-af45-e3b745ca0035
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Website Content"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "src/content/homepage.yml"
        fields:
          - label: "Business Name"
            name: "business_name"
            widget: "string"
          - label: "Phone"
            name: "phone"
            widget: "string"
          - label: "Homepage Photo"
            name: "hero_image"
            widget: "image"
